# Generated by Django 4.0.6 on 2025-01-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='tareas/')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='entregas/')),
                ('fecha_entrega', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.estudiante')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clases.tarea')),
            ],
        ),
    ]
