# Generated by Django 4.0.6 on 2025-01-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entregatarea',
            old_name='id_entrega',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='id_estudiante',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='id_profesor',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='id_tarea',
            new_name='id',
        ),
    ]
